version: '3.8'

services:
  app:
    image: storybooks-app:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - storybooks-network
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    environment:
      - MONGO_INITDB_DATABASE=storybooks
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - storybooks-network
    volumes:
      - mongodata:/data/db

networks:
  storybooks-network:
    driver: bridge

volumes:
  mongodata:
    driver: local
